# Generated by Django 3.0.6 on 2021-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture_template',
            name='lecture_descript',
            field=models.TextField(),
        ),
    ]
