# Generated by Django 3.0.6 on 2021-09-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20210920_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Aula'},
        ),
        migrations.AlterModelOptions(
            name='lecture_template',
            options={'verbose_name': 'Template'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aulas.Lecture_template'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
