# Generated by Django 3.0.6 on 2021-09-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_auto_20210920_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aluno',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='attendees',
            field=models.ManyToManyField(to='aulas.Student'),
        ),
    ]
